
package principal.juegoserpientee;

import principal.juegoserpientee.fondo;
import principal.juegoserpientee.Serpiente;
import java.awt.event.KeyEvent;


public class vistajuego extends javax.swing.JFrame {

    
    Serpiente serpiente;
    
    public vistajuego() {
        initComponents();
        this.setTitle("Juego de la Serpiente");
      this.setLocationRelativeTo(null);
        this.setSize(830, 880); // Ajustar tamaño de la ventana
        this.setResizable(false); // Evitar que el usuario cambie el tamaño de la ventana
        this.setLocation(300, 20); // Estable
        serpiente = new Serpiente( 800 , 30);
        this.add(serpiente);
        serpiente.setBounds(10,10,800,800);
        serpiente.setOpaque(false);
        
        fondo Fondo = new fondo( 800 , 30); 
        this.add(Fondo);
        Fondo.setBounds(10,10,800,800);
        
        this.pack(); // Ajustar tamaño de la ventana a los componentes
        this.setSize(830, 850); // Asegurar el tamaño de la ventana
        this.setResizable(false); // Evitar que el usuario cambie el tamaño de la ventana
        this.requestFocus(true);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    
    
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                serpiente.cambiardireccion("iz");
                break;
            case KeyEvent.VK_RIGHT:
                serpiente.cambiardireccion("de");
                break;
            case KeyEvent.VK_UP:
                serpiente.cambiardireccion("ar");
                break;
            case KeyEvent.VK_DOWN:
                serpiente.cambiardireccion("ab");
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
